/** Name suggestions for a new firm. Norwegian on purpose: the market is Norwegian whatever language you play in. */
export const FIRM_NAME_SUGGESTIONS = [
  'Konsulent & Konsulent AS',
  'Synergi Solutions',
  'Fakturerbar AS',
  'Nordlys Digital',
  'Kaffe & Kode',
  'Timeliste Group',
  'Fakturamaskinen AS',
  'Timepris & Sønn',
  'Powerpoint Partners',
  'Workshop Workshop AS',
  'Post-it Partners',
  'Smidig & Smidigere',
  'Standup Comedy AS',
  'Sprintløpet',
  'Backlog Brothers',
  'Jira & Jarle',
  'Retro Rådgivning',
  'Gantt Gruppen',
  'Excel-lent AS',
  'Pivot Partners',
  'Disrupt & Dusj',
  'Skybasert Skepsis AS',
  'Mikrotjeneste & Makrofaktura',
  'Legacy Legends',
  'Teknisk Gjeld AS',
  'Refaktor Rasmussen',
  'Kodegjennomgang & Kanelbolle',
  'Lunsjmøte Ltd',
  'Brunost Byte',
  'Fjord & Frontend',
  'Fjell & Fullstack',
  'Bergen Backend Bureau',
  'Trondheim Tech-ish',
  'Tromsø Tjenester i Skyen',
  'Kanban & Kaffekopp',
  'Den Agile Elg',
  'Elgen Konsulenter',
  'Fjøsfiber AS',
  'Vaffel & Velocity',
  'Kvikklunsj Konsult',
  'Matpakke Digital',
  'Pålegg Partners',
  'Leverpostei Labs',
  'Hyttetur & Hyperskalering',
  'Dugnad as a Service',
  'Fredagspils Forretningsutvikling',
  'Synergi i Andre AS',
  'Blokkjede & Blokkfløyte',
  'KI & Kanskje',
  'Prompt & Presis AS',
  'Halvferdig Holding',
  'Nesten i Prod AS',
  'Funker Lokalt AS',
  'Det Var Ikke Meg AS',
  'Rollback Rådgivning',
  'Hotfix & Hjertevarme',
  'Fredagsdeploy AS',
  'Mandagsmøte Management',
  'Lyden av Tastatur AS',
  'Tankesmie & Tastetrykk',
  'Hjernestorm Holding',
  'Helhetlig Helhet AS',
  'Verdiskaping & Venner',
  'Strategi & Strikk',
  'Moden Organisasjon AS',
  'Roadmap & Rosiner',
  'Kvartalstall & Kakao',
  'Interessentkartet AS',
  'Løsningsorientert Løsning AS',
  'Kunden Har Alltid Budsjett AS',
  'Scope Creep & Co.',
  'Tidsestimat Ca. AS',
  'Omtrent Agile',
  'Sky High Consulting',
  'Wifi & Visjon',
  'Ladekabel Consulting',
  'Skjermdeling Solutions',
  'Du Er På Mute AS',
  'Kamera Av Konsult',
  'Hører Dere Meg Group',
  'Teams & Tålmodighet',
  'Kalenderkollisjon AS',
  'Dobbeltbooket Group',
  'Fakturert & Fornøyd',
  'Timer & Tillit',
  'Gummiand Konsulenter',
  'Rubber Duck Rådgivning',
  'Tre Konsulenter i en Trenchcoat',
  'Noen Fra IT AS',
  'Han Som Kan Excel AS',
  'Data & Drømmer',
  'Dashbord & Dagdrøm',
  'Pixel & Pålegg',
  'Brukerreise & Baguette',
  'Design Thinking Thinking AS',
  'MVP & Mjød',
  'Proof of Konsept AS',
  'Pilotprosjekt Permanent AS',
  'Midlertidig Løsning Siden 2027',
  'Innovasjon Innovasjon Innovasjon',
  'Buzzword Bingo Group',
  'Leverbart AS',
  'Faktisk Agile AS',
  'Kaffemaskinen Er Ødelagt AS',
  'Gründer & Grandiosa',
  'Rakfisk & Rammeavtale',
  'Pinnekjøtt & Prosjektledelse',
  'Lefse Labs',
  'Tacofredag Tech',
  'Ostehøvel Optimering',
  'Anbud & Ambisjoner',
  'Rammeavtale & Romantikk',
  'Fagmiljø Forever',
  'Benken Brenner AS',
  'Kodekveld & Kakao Holding',
  'Allerede Avtalt AS',
  'Agenda Følger AS',
  'Mange Bekker Små',
  'Skalerbar Skolebolle',
  'Kontorhund Konsult',
] as const

/** A random suggestion that isn't the name already in the field. */
export function suggestFirmName(current: string): string {
  const pool = FIRM_NAME_SUGGESTIONS.filter((n) => n !== current)
  return pool[Math.floor(Math.random() * pool.length)]
}
