import type { EventCtx } from './events'

export interface AnnouncementDef {
  id: string
  weight: number
  condition?: (ctx: EventCtx) => boolean
  /** Uses a random star's first name as {{name}}. */
  needsStar?: boolean
}

export const ANNOUNCEMENTS: AnnouncementDef[] = [
  { id: 'mug_meeting_room', weight: 1, needsStar: true },
  { id: 'friday_beer_alcohol_free', weight: 1 },
  { id: 'fridge_cleanup', weight: 1 },
  { id: 'printer_on_fire', weight: 0.5 },
  { id: 'wifi_password', weight: 1 },
  { id: 'standup_standing', weight: 1 },
  { id: 'cake_in_kitchen', weight: 1 },
  { id: 'timesheet_reminder', weight: 1.5 },
  { id: 'lost_macbook_charger', weight: 1 },
  { id: 'fire_drill', weight: 0.7 },
  { id: 'parking_spot', weight: 0.8, needsStar: true },
  { id: 'jira_down', weight: 1 },
  { id: 'someone_microwaved_fish', weight: 1 },
  { id: 'meeting_room_hostage', weight: 1 },
  { id: 'sprint_retro_cake', weight: 0.8 },
  { id: 'dress_code', weight: 0.6 },
  { id: 'intern_lost', weight: 0.6 },
  { id: 'ceo_birthday', weight: 0.5 },
  { id: 'coffee_beans_out', weight: 1, condition: ({ firm }) => firm.sosialt < 40 },
  { id: 'fagdag_room', weight: 1, condition: ({ firm }) => firm.fagmiljo >= 50 },
  { id: 'kombucha_on_tap', weight: 1, condition: ({ firm }) => firm.sosialt >= 60 },
  { id: 'bench_reminder', weight: 2, condition: ({ utilization }) => utilization < 0.6 },
  { id: 'overtime_pizza', weight: 2, condition: ({ utilization }) => utilization > 0.95 },
  { id: 'compliance_tor', weight: 2, condition: ({ firm }) => firm.heat > 30 },
  { id: 'shredder_busy', weight: 2, condition: ({ firm }) => firm.heat > 50 },
  { id: 'journalists_in_lobby', weight: 1.5, condition: ({ firm }) => firm.heat > 60 },
  { id: 'morale_survey', weight: 2, condition: ({ morale }) => morale < 50 },
  { id: 'pingpong_final', weight: 1, condition: ({ firm }) => firm.sosialt >= 50 },
  { id: 'new_office_plants', weight: 1, condition: ({ headcount }) => headcount >= 20 },
  { id: 'elevator_pitch', weight: 1, condition: ({ headcount }) => headcount >= 50 },
  { id: 'small_office', weight: 1.5, condition: ({ headcount }) => headcount < 10 },
  { id: 'cash_low', weight: 2, condition: ({ firm }) => firm.cash < 1_000_000 },
  { id: 'printer_toner', weight: 1 },
  { id: 'teams_status', weight: 1 },
  { id: 'dishwasher', weight: 1 },
  { id: 'reply_all', weight: 1 },
  { id: 'standing_desk', weight: 1 },
  { id: 'lunch_menu', weight: 1 },
  { id: 'badge_forgotten', weight: 1 },
  { id: 'mute_button', weight: 1 },
  { id: 'password_policy', weight: 1 },
  { id: 'okr_workshop', weight: 1 },
  { id: 'whiteboard', weight: 1 },
  { id: 'slack_channels', weight: 1 },
  { id: 'air_con', weight: 1 },
  { id: 'fruit_bowl', weight: 1 },
  { id: 'lost_airpod', weight: 1 },
  { id: 'calendar_invite', weight: 1 },
  { id: 'code_freeze', weight: 1 },
  { id: 'hackathon', weight: 1 },
  { id: 'coat_rack', weight: 1 },
  { id: 'microwave_queue', weight: 1 },
  { id: 'agile_coach', weight: 1 },
  { id: 'bike_room', weight: 1 },
  { id: 'plastic_plant', weight: 1 },
  { id: 'confluence_updated', weight: 1 },
  { id: 'mechanical_keyboard', weight: 1 },
  { id: 'vpn_slow', weight: 1 },
  { id: 'quiz_night', weight: 1 },
  { id: 'phone_booth', weight: 1 },
  { id: 'expense_receipts', weight: 1 },
  { id: 'coffee_machine_options', weight: 1 },
  { id: 'laptop_updates', weight: 1 },
  { id: 'star_podcast', weight: 0.7, needsStar: true },
  { id: 'star_linkedin', weight: 0.7, needsStar: true },
  { id: 'star_deep_work', weight: 0.7, needsStar: true },
  { id: 'star_sourdough', weight: 0.7, needsStar: true },
  { id: 'new_year_gym', weight: 1.5, condition: ({ state }) => state.quarter % 4 === 0 },
  { id: 'easter_quiz', weight: 1.5, condition: ({ state }) => state.quarter % 4 === 1 },
  { id: 'may_17', weight: 1.5, condition: ({ state }) => state.quarter % 4 === 1 },
  { id: 'back_from_holiday', weight: 1.5, condition: ({ state }) => state.quarter % 4 === 2 },
  { id: 'summer_students', weight: 1.5, condition: ({ state }) => state.quarter % 4 === 2 },
  { id: 'christmas_party', weight: 1.5, condition: ({ state }) => state.quarter % 4 === 3 },
  { id: 'secret_santa', weight: 1.5, condition: ({ state }) => state.quarter % 4 === 3 },
  { id: 'budget_season', weight: 1.5, condition: ({ state }) => state.quarter % 4 === 3 },
  { id: 'legal_hold', weight: 1.5, condition: ({ firm }) => firm.heat > 40 },
  { id: 'lawyers_back', weight: 2, condition: ({ firm }) => firm.heat > 70 },
  { id: 'whistleblower_channel', weight: 1.5, condition: ({ firm }) => firm.heat > 30 },
  { id: 'compliance_bored', weight: 1, condition: ({ firm }) => firm.heat < 10 },
  { id: 'media_training', weight: 2, condition: ({ firm }) => firm.scandalPenalty > 0 },
  { id: 'trophy_shelf', weight: 1.5, condition: ({ firm }) => firm.reputation >= 70 },
  { id: 'new_logo', weight: 1.5, condition: ({ firm }) => firm.reputation < 30 },
  { id: 'overdraft_hello', weight: 2, condition: ({ firm }) => firm.cash < 0 },
  { id: 'weekend_open', weight: 1.5, condition: ({ utilization }) => utilization > 0.95 },
  { id: 'bench_workshop', weight: 1.5, condition: ({ utilization }) => utilization < 0.6 },
  { id: 'record_morale', weight: 1.5, condition: ({ morale }) => morale >= 75 },
  { id: 'exit_interviews', weight: 2, condition: ({ morale }) => morale < 35 },
  { id: 'lunch_talk_monads', weight: 1.5, condition: ({ firm }) => firm.fagmiljo >= 70 },
  { id: 'build_server', weight: 1.5, condition: ({ firm }) => firm.fagmiljo < 25 },
  { id: 'company_choir', weight: 1.5, condition: ({ firm }) => firm.sosialt >= 70 },
  { id: 'social_two_came', weight: 1.5, condition: ({ firm }) => firm.sosialt < 30 },
  { id: 'name_tags', weight: 1, condition: ({ headcount }) => headcount >= 100 },
  { id: 'all_hands_coffee', weight: 1.5, condition: ({ headcount }) => headcount < 5 },
  { id: 'share_price_screen', weight: 1.5, condition: ({ firm }) => !!firm.listed },
  { id: 'quiet_period', weight: 1.5, condition: ({ firm }) => !!firm.listed },
  { id: 'corner_office', weight: 1, condition: ({ firm }) => (firm.level ?? 1) >= 3 },
  { id: 'business_cards', weight: 1.5, condition: ({ firm }) => (firm.level ?? 1) <= 1 },
  { id: 'strategy_2037', weight: 2, condition: ({ state }) => state.quarter >= 36 },
  { id: 'new_premises', weight: 1.5, condition: ({ state }) => state.quarter <= 3 },
  { id: 'offshore_standup', weight: 1.5, condition: ({ state, firm }) => state.contracts.some((c) => c.firmId === firm.id && !c.terminated && c.outsourcedShare > 0) },
]
