import type { MeetingStyle } from '../engine/types'

/** Question ids. Each has four answers, one per style. Texts in minigames.meeting.questions.<id>. */
export const MEETING_QUESTIONS = [
  'continuity',
  'public_sector',
  'start_monday',
  'changes',
  'why_you',
  'price',
  'security',
  'team',
  'legacy',
  'ai',
  'dlv_waterfall',
  'dlv_deadline_slip',
  'dlv_testing',
  'dlv_code_review',
  'dlv_documentation',
  'dlv_handover',
  'dlv_status_reports',
  'dlv_meetings',
  'dlv_risk',
  'dlv_other_vendors',
  'dlv_mvp',
  'dlv_prioritisation',
  'dlv_success_metrics',
  'dlv_user_involvement',
  'dlv_go_live',
  'dlv_on_call',
  'dlv_incident',
  'dlv_tech_debt',
  'dlv_inhouse_staff',
  'dlv_steering_committee',
  'dlv_sprint_length',
  'dlv_demo',
  'dlv_bad_news',
  'dlv_definition_of_done',
  'dlv_requirements_spec',
  'dlv_productivity',
  'dlv_scope_creep',
  'dlv_test_environment',
  'dlv_release_frequency',
  'dlv_contact',
  'dlv_vendor_delay',
  'dlv_retrospective',
  'dlv_product_owner',
  'dlv_summer_holiday',
  'dlv_budget_tracking',
  'dlv_user_training',
  'dlv_prototype',
  'dlv_monitoring',
  'dlv_tech_decisions',
  'dlv_rollback',
  'dlv_pair_programming',
  'dlv_green_status',
  'ppl_seniority_mix',
  'ppl_resigns',
  'ppl_sick_leave',
  'ppl_turnover',
  'ppl_recruiting',
  'ppl_onboarding',
  'ppl_courses',
  'ppl_certifications',
  'ppl_diversity',
  'ppl_office_days',
  'ppl_hybrid',
  'ppl_overtime',
  'ppl_work_life',
  'ppl_conflict',
  'ppl_bad_fit',
  'ppl_team_lead',
  'ppl_domain',
  'ppl_norwegian',
  'ppl_clearance',
  'ppl_values',
  'ppl_culture_word',
  'ppl_fagmiljo',
  'ppl_knowledge_sharing',
  'ppl_friday_drinks',
  'ppl_cabin_trip',
  'ppl_motivation',
  'ppl_burnout',
  'ppl_mentoring',
  'ppl_junior_billing',
  'ppl_senior_hands_on',
  'ppl_bench',
  'ppl_parental_leave',
  'ppl_underperform',
  'ppl_feedback',
  'ppl_one_team',
  'ppl_train_staff',
  'ppl_hire_away',
  'ppl_age',
  'ppl_scale_up',
  'ppl_dress_code',
  'ppl_working_hours',
  'ppl_account_follow_up',
  'ppl_tenure',
  'ppl_soft_skills',
  'ppl_speak_up',
  'ppl_learning_days',
  'tec_cloud_provider',
  'tec_vendor_lockin',
  'tec_open_source',
  'tec_microservices',
  'tec_architecture_decisions',
  'tec_data_driven',
  'tec_data_quality',
  'tec_gdpr',
  'tec_accessibility',
  'tec_accessibility_audit',
  'tec_passwords',
  'tec_pentest',
  'tec_supply_chain',
  'tec_logging',
  'tec_security_incident',
  'tec_performance',
  'tec_peak_load',
  'tec_app_vs_web',
  'tec_offline',
  'tec_design_system',
  'tec_tech_stack',
  'tec_new_framework',
  'tec_api',
  'tec_integrations',
  'tec_migration',
  'tec_cloud_cost',
  'tec_data_location',
  'tec_devops',
  'tec_backup',
  'tec_disaster_recovery',
  'tec_green_it',
  'tec_chatbot',
  'tec_ai_own_data',
  'tec_ai_code',
  'tec_ai_risk',
  'tec_low_code',
  'tec_login',
  'tec_national_components',
  'tec_archiving',
  'tec_spreadsheet',
  'tec_realtime',
  'tec_open_data',
  'tec_search',
  'com_fixed_price',
  'com_discount',
  'com_budget_overrun',
  'com_change_orders',
  'com_sla_penalties',
  'com_references',
  'com_biggest_failure',
  'com_first_30_days',
  'com_competitors',
  'com_smaller_firm',
  'com_bigger_firm',
  'com_subcontractors',
  'com_conflict_interest',
  'com_know_us',
  'com_industry',
  'com_value_money',
  'com_late',
  'com_invoicing',
  'com_exit_clause',
  'com_call_offs',
  'com_partnership',
  'com_measure_success',
  'com_estimates',
  'com_code_ownership',
  'com_warranty',
  'com_travel_expenses',
  'com_price_increase',
  'com_liability',
  'com_trial_job',
  'com_lost_last_tender',
  'cur_questions_for_us',
  'cur_three_words',
  'cur_worst_client',
  'cur_animal',
  'cur_last_client_left',
  'cur_coffee',
  'cur_projector_dies',
  'cur_half_price',
  'cur_blockchain',
  'cur_weakness',
  'cur_five_years',
  'cur_why_consultant',
  'cur_explain_like_five',
  'cur_arrived_late',
  'cur_superpower',
  'cur_said_no',
  'cur_two_minutes',
  'cur_promised_moon',
  'sec_hospital_clinicians',
  'sec_hospital_always_on',
  'sec_kommune_one_it_person',
  'sec_kommune_merger',
  'sec_bank_inspection',
  'sec_bank_fraud',
  'sec_retail_change_freeze',
  'sec_retail_abandoned_cart',
  'sec_energy_sensors',
  'sec_energy_isolated_network',
  'sec_transport_realtime',
  'sec_transport_winter',
  'sec_edu_exam_day',
  'sec_edu_teachers',
  'sec_media_paywall',
  'sec_media_newsroom',
  'sec_insurance_claims',
  'sec_insurance_driving_data',
  'sec_logistics_gloves',
  'sec_logistics_trucks_waiting',
  'sec_startup_equity',
  'sec_startup_cloud_credits',
  'sec_ministry_unpassed_law',
  'sec_ministry_press_conference',
  'sec_members_board_passwords',
] as const

export type MeetingQuestion = (typeof MEETING_QUESTIONS)[number]

/** Questions that only make sense from one kind of customer. The rest are asked by anyone. */
export const QUESTION_SECTOR: Partial<Record<MeetingQuestion, 'public' | 'private'>> = {
  public_sector: 'public',
  tec_national_components: 'public',
  tec_archiving: 'public',
  sec_hospital_clinicians: 'public',
  sec_hospital_always_on: 'public',
  sec_kommune_one_it_person: 'public',
  sec_kommune_merger: 'public',
  sec_edu_exam_day: 'public',
  sec_edu_teachers: 'public',
  sec_transport_realtime: 'public',
  sec_transport_winter: 'public',
  sec_ministry_unpassed_law: 'public',
  sec_ministry_press_conference: 'public',
  sec_bank_inspection: 'private',
  sec_bank_fraud: 'private',
  sec_retail_change_freeze: 'private',
  sec_retail_abandoned_cart: 'private',
  sec_media_paywall: 'private',
  sec_media_newsroom: 'private',
  sec_insurance_claims: 'private',
  sec_insurance_driving_data: 'private',
  sec_logistics_gloves: 'private',
  sec_logistics_trucks_waiting: 'private',
  sec_startup_equity: 'private',
  sec_startup_cloud_credits: 'private',
  sec_members_board_passwords: 'private',
}

export const MEETING_STYLES: MeetingStyle[] = ['concrete', 'visionary', 'humble', 'buzzword']

export const OPPOSITE_STYLE: Record<MeetingStyle, MeetingStyle> = {
  concrete: 'visionary',
  visionary: 'concrete',
  humble: 'buzzword',
  buzzword: 'humble',
}
