import type { SongSpec } from './compose'

/**
 * The background music: twenty small tunes in the spirit of 90s tycoon games (swing, ragtime,
 * shuffle blues and a little bossa). Each song is chords plus a style; `compose()` writes the rest.
 * Titles live in `ui:music.songs.<id>`.
 */
export const SONGS: SongSpec[] = [
  {
    id: 'timesheetShuffle',
    bpm: 132,
    swing: true,
    sections: {
      A: ['F6', 'D7', 'Gm7', 'C7', 'Am7 D7', 'Gm7 C7', 'F6', 'Gm7 C7'],
      B: ['A7', 'A7', 'Dm7', 'Dm7', 'G7', 'G7', 'Gm7', 'C7'],
    },
    form: 'AABA',
    end: 'F6',
    lead: 'clarinet',
    comp: 'charleston',
    bass: 'walk',
    drums: 'swing',
  },
  {
    id: 'coffeeMachineRag',
    bpm: 112,
    swing: false,
    sections: {
      A: ['C', 'C', 'G7', 'G7', 'G7', 'G7', 'C', 'C'],
      B: ['F', 'F', 'C', 'A7', 'D7', 'G7', 'C', 'G7'],
    },
    form: 'AABB',
    end: 'C',
    lead: 'piano',
    comp: 'stride',
    bass: 'none',
    drums: 'march',
  },
  {
    id: 'billableBlues',
    bpm: 104,
    swing: true,
    sections: {
      A: ['Bb7', 'Eb7', 'Bb7', 'Bb7', 'Eb7', 'Eb7', 'Bb7', 'G7', 'Cm7', 'F7', 'Bb7 G7', 'Cm7 F7'],
    },
    form: 'AA',
    end: 'Bb7',
    lead: 'brass',
    comp: 'charleston',
    bass: 'boogie',
    drums: 'shuffle',
  },
  {
    id: 'quarterlyBossa',
    bpm: 126,
    swing: false,
    sections: {
      A: ['Dm7', 'Dm7', 'Em7b5', 'A7b9', 'Dm7', 'Gm7 C7', 'Fmaj7', 'Em7b5 A7'],
      B: ['Gm7', 'C7', 'Fmaj7', 'Bbmaj7', 'Em7b5', 'A7', 'Dm7', 'A7'],
    },
    form: 'AABA',
    end: 'Dm6',
    lead: 'flute',
    comp: 'bossa',
    bass: 'bossa',
    drums: 'bossa',
  },
  {
    id: 'openOfficeSwing',
    bpm: 144,
    swing: true,
    sections: {
      A: ['Gmaj7', 'Em7', 'Am7', 'D7', 'Bm7 E7', 'Am7 D7', 'G6', 'Am7 D7'],
      B: ['Cmaj7', 'Cm6', 'Bm7', 'E7', 'A7', 'A7', 'Am7', 'D7'],
    },
    form: 'AABA',
    end: 'G6',
    lead: 'square',
    comp: 'charleston',
    bass: 'walk',
    drums: 'swing',
  },
  {
    id: 'deadlineDrive',
    bpm: 150,
    swing: true,
    sections: {
      A: ['Eb6', 'C7', 'Fm7', 'Bb7', 'Gm7 C7', 'Fm7 Bb7', 'Eb6', 'Fm7 Bb7'],
      B: ['G7', 'G7', 'Cm7', 'Cm7', 'F7', 'F7', 'Fm7', 'Bb7'],
    },
    form: 'AABA',
    end: 'Eb6',
    lead: 'brass',
    comp: 'charleston',
    bass: 'walk',
    drums: 'swing',
    busy: true,
  },
  {
    id: 'kpiCakewalk',
    bpm: 116,
    swing: false,
    sections: {
      A: ['G', 'G', 'D7', 'G', 'G', 'E7', 'A7 D7', 'G'],
      B: ['C', 'C', 'G', 'E7', 'A7', 'D7', 'G', 'D7'],
    },
    form: 'AABB',
    end: 'G',
    lead: 'clarinet',
    comp: 'stride',
    bass: 'none',
    drums: 'march',
  },
  {
    id: 'agileSunrise',
    bpm: 96,
    swing: true,
    sections: {
      A: ['Dmaj7', 'Bm7', 'Em7', 'A7', 'F#m7', 'B7', 'Em7', 'A7'],
      B: ['Gmaj7', 'Gm6', 'F#m7', 'B7', 'Em7', 'A7', 'Dmaj7', 'A7'],
    },
    form: 'AABA',
    end: 'Dmaj7',
    lead: 'vibes',
    comp: 'pad',
    bass: 'two',
    drums: 'brush',
  },
  {
    id: 'invoiceBoogie',
    bpm: 138,
    swing: true,
    sections: {
      A: ['C7', 'F7', 'C7', 'C7', 'F7', 'F7', 'C7', 'A7', 'Dm7', 'G7', 'C7 A7', 'Dm7 G7'],
    },
    form: 'AA',
    end: 'C7',
    lead: 'square',
    comp: 'twoFour',
    bass: 'boogie',
    drums: 'shuffle',
    busy: true,
  },
  {
    id: 'overtimeLounge',
    bpm: 88,
    swing: true,
    sections: {
      A: ['Abmaj7', 'Fm7', 'Bbm7', 'Eb7', 'Cm7 F7', 'Bbm7 Eb7', 'Abmaj7', 'Bbm7 Eb7'],
      B: ['Dbmaj7', 'Dbm6', 'Cm7', 'F7', 'Bb7', 'Bb7', 'Bbm7', 'Eb7'],
    },
    form: 'AABA',
    end: 'Abmaj7',
    lead: 'flute',
    comp: 'pad',
    bass: 'walk',
    drums: 'brush',
  },
  {
    id: 'budgetMarch',
    bpm: 120,
    swing: false,
    sections: {
      A: ['Am', 'E7', 'Am', 'E7', 'Am', 'Dm', 'E7', 'Am'],
      B: ['C', 'G7', 'C', 'E7', 'Am', 'Dm6', 'E7', 'Am'],
    },
    form: 'AABB',
    end: 'Am',
    lead: 'clarinet',
    comp: 'twoFour',
    bass: 'two',
    drums: 'march',
  },
  {
    id: 'synergySwing',
    bpm: 160,
    swing: true,
    sections: {
      A: ['Bb6 G7', 'Cm7 F7', 'Dm7 G7', 'Cm7 F7', 'Fm7 Bb7', 'Ebmaj7 Ab7', 'Dm7 G7', 'Cm7 F7'],
      B: ['D7', 'D7', 'G7', 'G7', 'C7', 'C7', 'F7', 'F7'],
    },
    form: 'AABA',
    end: 'Bb6',
    lead: 'square',
    solo: 'vibes',
    comp: 'charleston',
    bass: 'walk',
    drums: 'swing',
  },
  {
    id: 'elevatorPitch',
    bpm: 118,
    swing: false,
    sections: {
      A: ['Fmaj7', 'Fmaj7', 'Gm7', 'C7', 'Am7', 'D7b9', 'Gm7', 'C7'],
      B: ['Bbmaj7', 'Bbm6', 'Am7', 'D7', 'Gm7', 'C7', 'Fmaj7', 'C7'],
    },
    form: 'AABA',
    end: 'Fmaj7',
    lead: 'vibes',
    solo: 'flute',
    comp: 'bossa',
    bass: 'bossa',
    drums: 'bossa',
  },
  {
    id: 'serverRoomStomp',
    bpm: 120,
    swing: true,
    sections: {
      A: ['E7', 'A7', 'E7', 'E7', 'A7', 'A7', 'E7', 'C#7', 'F#m7', 'B7', 'E7 C#7', 'F#m7 B7'],
    },
    form: 'AA',
    end: 'E7',
    lead: 'brass',
    solo: 'square',
    comp: 'twoFour',
    bass: 'boogie',
    drums: 'shuffle',
  },
  {
    id: 'commuterCruise',
    bpm: 124,
    swing: true,
    sections: {
      A: ['Cmaj7', 'Am7', 'Dm7', 'G7', 'Em7 A7', 'Dm7 G7', 'Cmaj7', 'Dm7 G7'],
      B: ['Fmaj7', 'Fm6', 'Em7', 'A7', 'D7', 'D7', 'Dm7', 'G7'],
    },
    form: 'AABA',
    end: 'Cmaj7',
    lead: 'piano',
    comp: 'charleston',
    bass: 'walk',
    drums: 'brush',
  },
  {
    id: 'minorMilestones',
    bpm: 140,
    swing: true,
    sections: {
      A: ['Am6', 'Am6', 'Dm6', 'Dm6', 'E7', 'E7', 'Am6', 'Am6'],
      B: ['Dm6', 'Dm6', 'Am6', 'Am6', 'B7', 'E7', 'Am6', 'E7'],
    },
    form: 'AABA',
    end: 'Am6',
    lead: 'clarinet',
    comp: 'charleston',
    bass: 'two',
    drums: 'swing',
    busy: true,
  },
  {
    id: 'strategyDayRag',
    bpm: 108,
    swing: false,
    sections: {
      A: ['F', 'F', 'C7', 'C7', 'C7', 'C7', 'F', 'F'],
      B: ['Bb', 'Bbm6', 'F', 'D7', 'G7', 'C7', 'F', 'C7'],
    },
    form: 'AABB',
    end: 'F',
    lead: 'square',
    comp: 'stride',
    bass: 'none',
    drums: 'march',
  },
  {
    id: 'fridayDrinks',
    bpm: 136,
    swing: true,
    sections: {
      A: ['G6', 'Gdim7', 'Am7', 'D7', 'G6 E7', 'Am7 D7', 'G6', 'D7'],
      B: ['B7', 'B7', 'E7', 'E7', 'A7', 'A7', 'Am7', 'D7'],
    },
    form: 'AABA',
    end: 'G6',
    lead: 'brass',
    comp: 'charleston',
    bass: 'walk',
    drums: 'swing',
  },
  {
    id: 'nightShift',
    bpm: 84,
    swing: true,
    sections: {
      A: ['Ebmaj7', 'Cm7', 'Fm7', 'Bb7', 'Gm7', 'C7', 'Fm7', 'Bb7'],
      B: ['Abmaj7', 'Abm6', 'Gm7', 'C7', 'F7', 'F7', 'Fm7', 'Bb7'],
    },
    form: 'AABA',
    end: 'Ebmaj7',
    lead: 'vibes',
    solo: 'clarinet',
    comp: 'pad',
    bass: 'two',
    drums: 'brush',
  },
  {
    id: 'goldenParachute',
    bpm: 148,
    swing: true,
    sections: {
      A: ['C6', 'A7', 'D7', 'G7', 'C6 A7', 'Dm7 G7', 'C6', 'G7'],
      B: ['E7', 'E7', 'A7', 'A7', 'D7', 'D7', 'G7', 'G7'],
    },
    form: 'AABA',
    end: 'C6',
    lead: 'square',
    solo: 'brass',
    comp: 'charleston',
    bass: 'walk',
    drums: 'swing',
    busy: true,
  },
]
